import 'package:flutter/material.dart';

List<Color> myColors = [
  //Colors
  Color(0xffEF9200),
//

  Colors.green,
  Colors.lightGreen,
  Colors.lime,
  Colors.yellow,
  Colors.amber,
  Color(0xffE35520),
  Color(0xffE4E4E4),
  Color(0xff56BE00),
//Main Colors

  Colors.lightGreen,
  Colors.lime,
  Colors.yellow,
  Colors.amber,
  Color(0xfff69227),
  Color(0xff2089d6),
  Color(0xffe35520),
  Color(0xff2b9304),
  Color(0xff00a163),
  Color(0xffc3c3c3),
  Color(0xff212f49),
  Color(0xff6c6c6c),
  Color(0xfff6921e),
//for course container
  Colors.red,
  Colors.pink,
  Colors.purple,
  Colors.deepPurple,
  Colors.indigo,
  Colors.blue,
  Colors.lightBlue,

  Color(0xff2b9304),
  Color(0xff00a163),
  Color(0xffc3c3c3),

  Colors.lightGreen,
  Colors.lime,
  Colors.yellow,
  Colors.amber,
  Color(0xff00a163),
  Color(0xffc3c3c3),
  Color(0xff212f49),
  Color(0xff6c6c6c),
  Color(0xfff6921e),
  Colors.pink,
  Colors.purple,
  Colors.deepPurple,

  Color(0xff00a163),
  Color(0xffc3c3c3),
  Color(0xff212f49),
  Color(0xff6c6c6c),
  Color(0xfff6921e),
  Colors.indigo,
  Colors.blue,
  Colors.lightBlue,
  Color(0xff212f49),

  Colors.lightGreen,
  Colors.lime,
  Colors.yellow,
  Colors.amber,
  Color(0xff6c6c6c),
  Color(0xfff6921e),
  Colors.cyan,
  Colors.teal,
  Colors.green,
  Colors.lightGreen,
  Colors.lime,
  Colors.yellow,
  Colors.amber,
  Colors.orange,

  Colors.deepOrange,
  Colors.brown,
  Color(0xff6aca01),
  Color(0xff448bde),
  Color(0xffcd67f7),

  Colors.lightGreen,
  Colors.lime,
  Colors.yellow,
  Colors.amber,
  Color(0xffc769fc),

  Colors.green,
  Colors.lightGreen,
  Colors.lime,
  Colors.yellow,

  Colors.indigo,
  Colors.blue,
  Colors.lightBlue,
  Color(0xffe39200),
  Colors.amber,
  Color(0xffd35500),

  Colors.lightGreen,
  Colors.lime,
  Colors.yellow,
  Colors.amber,

  Colors.indigo,
  Colors.blue,
  Colors.lightBlue,
  Color(0xffe39200),
  Colors.pink,
  Colors.purple,
  Colors.deepPurple,

  Colors.lightGreen,
  Colors.lime,
  Colors.yellow,
  Colors.amber,
  Colors.indigo,
  Colors.blue,
  Colors.lightBlue,
  Color(0xffe39200),
];
const kWhiteColor = Color(0xffE4E4E4);
